### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [nname123/git-workshop#1]
你 readme 中提到到問題比較難用文字解釋，主要是如果這個 repo 是從 github 上 clone 下來的，那就不需要再加上一次 remote，關於這點，你要先理解 remote 是什麼意思？你可以先試著回答我看看嗎？

再來是 master 跟 main 都是分支名稱，master 是歷史包袱，現在都是建議使用 main 這個名稱。

至於本地分支、遠端分支這個，需要下次上課時，你來找我，我畫圖給你看，比較好說明，好嗎？

**Comment by azole** [comment]
![image](https://user-images.githubusercontent.com/2560515/203925606-6dc19695-08f8-47d8-8f52-6d7685748f36.png)

我們本地跟遠端(例如 github 上)聯繫的方式有兩種: HTTPS 跟 SSH，如果你 clone 的時候複製的是 HTTPS 這邊的網址，那就在 push 時會需要輸入帳號密碼，要用 SSH 這邊這個網址 clone，才會是用 SSH 的方式。

你可以手動實驗一下，分別用兩種方式 clone 到不同檔案夾裡，然後觀察一下 clone 下來的專案裡的 .git/config 這個設定檔，應該會看到不同的設定結果。

**Comment by nname123** [comment]
謝謝老師的回覆
我知道ssh/https的差別了，我有記錄在readme.md

remote 我認為是遠端的意思
git remote add origin {url} 這段是新增與遠端的連結
我原本以為檔案連線到GitHub都需要用remote的指令，老師講完後我發現如果是從Github抓下來其實只需要clone就可以了，現在我已經明白了

master 改 main 我記得老師上課有解釋，我知道要用main比較好
本地分支、遠端分支這個下次上課我會去請教老師，謝謝老師

**Comment by azole** [comment]
你是有來提醒我的同學嗎？但好像還是沒有講到？ 如果是的話，拜託下次再提醒我一次  🙏  謝謝

**Comment by nname123** [comment]
沒錯我上周六有去問老師,我這周六會再去請教老師,謝謝~
